### ISSUE TITLE
lost all data in the DB

### ISSUE THREAD

**Issue by geohuz** [subzerocloud/postgrest-starter-kit#49]
After running docker-compose down then docker-compose restart /docker-compose up -d I found I've lost all my added tables and views in the database only left me with the starter-kit db objects(user, todo)

**Comment by ruslantalpa** [comment]
The starter kit database is configured specifically like that so that every time you do a down/up you get a clean system based only on the current (sql) files. When moving to production the setup is a bit different, most important part being that the database is independent (not running as a docker service) since this is [not advisable](https://vsupalov.com/database-in-docker/)

Here is a tutorial on how to setup your production env https://docs.subzero.cloud/production-infrastructure/aws-ecs-rds/ notice all of the services in the stack are running as docker containers (ECS) EXCEPT the database which is running in RDS. 

If you still want to run your database in docker and keep the data between the reboots you can do that by mounting a directory on the host using the volumes section (see here https://stackoverflow.com/questions/41637505/how-to-persist-data-in-a-dockerized-postgres-database-using-volumes)
